/**
 Generated by Multiple Back-Propagation Version 2.2.5
 Multiple Back-Propagation can be freely obtained at http://dit.ipg.pt/MBP
*/

#include <math.h>
/**
 inputs  - should be an array of 3 element(s), containing the network input(s).
 outputs - should be an array of 1 element(s), that will contain the network output(s).
 Note : The array inputs will also be changed.Its values will be rescaled between -1 and 1.
*/
void mainApp(double * inputs, double * outputs) {
	double mainWeights[] = {-5.304646968841553, -5.878194808959961, 2.774537801742554, -0.965698838233948, 1.300650835037231, -4.016737461090088, -2.394049644470215, -2.599856138229370, 4.499671936035156, -2.858046770095825, 2.551645755767822, -1.500937819480896, -3.759322404861450, -11.726829528808594, 3.583931207656860, 7.702889442443848};
	double * mw = mainWeights;
	double hiddenLayer1outputs[3];
	int c;

	inputs[0] = -1.0 + (inputs[0] - 1.000000000000000) / 1.000000000000000;
	inputs[1] = -1.0 + (inputs[1] - 1.000000000000000) / 0.500000000000000;
	inputs[2] = -1.0 + (inputs[2] - 1.000000000000000) / 0.500000000000000;
	hiddenLayer1outputs[0] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[0] += *mw++ * inputs[c];
	hiddenLayer1outputs[0] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[0]));
	hiddenLayer1outputs[1] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[1] += *mw++ * inputs[c];
	hiddenLayer1outputs[1] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[1]));
	hiddenLayer1outputs[2] = *mw++;
	for(c = 0; c < 3; c++) hiddenLayer1outputs[2] += *mw++ * inputs[c];
	hiddenLayer1outputs[2] = 1.0 / (1.0 + exp(-hiddenLayer1outputs[2]));
	outputs[0] = *mw++;
	for(c = 0; c < 3; c++) outputs[0] += *mw++ * hiddenLayer1outputs[c];
	outputs[0] = 1.0 / (1.0 + exp(-outputs[0]));
	outputs[0] = 0.000000000000000 + (outputs[0] - 0.000000) * 1.000000000000000;
}
